# Generated by Django 5.1.4 on 2025-01-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_favoriteteam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteteam',
            name='TeamID',
            field=models.IntegerField(null=True),
        ),
    ]
